In [1]:
import torch


In [6]:
w1 = torch.tensor([.23], requires_grad=True)
b = torch.tensor([.1], requires_grad=True)

In [7]:
x1= torch.tensor([1.23])
y= torch.tensor([1.])

In [10]:
z= w1*x1+b

In [11]:
a = torch.sigmoid(z)

In [13]:
import torch.nn.functional as F

In [14]:
L = F.binary_cross_entropy(a, y)

In [15]:
L

tensor(0.5199, grad_fn=<BinaryCrossEntropyBackward0>)

In [16]:
from torch.autograd import grad

In [19]:
grad_L_w1 = grad(L, w1, retain_graph=True)

In [20]:
grad_L_w1

(tensor([-0.4987]),)

In [21]:
grad_L_b = grad(L, b, retain_graph=True)

In [22]:
grad_L_b

(tensor([-0.4054]),)

In [23]:
L.backward()

In [26]:
w1.grad

tensor([-0.4987])

In [27]:
b.grad

tensor([-0.4054])

In [4]:
class MyList:
    def __init__(self, data):
        self.data = data
    
    def __getitem__(self, index):
        return self.data[index]

# Create an instance of MyList
my_list = MyList([1, 2, 3, 4, 5])

# Access elements using square bracket notation
print(my_list[0])  # Output: 1
print(my_list[3])  # Output: 4


1
4


In [7]:
print(my_list[0])

1


In [8]:
class CustomList:
    def __init__(self, data):
        self.data = data
        
    def __getitem__(self, index):
        return self.data[index]

In [9]:
c= CustomList([1, 2, 3, 4, 5])

In [12]:
print(c[-1])

5


In [16]:
class ParentClass:
    def __init__(self):
        print("ParentClass initialized")

class ChildClass(ParentClass):
    def __init__(self):
        # super().__init__()  # Call the constructor of the parent class
        print("ChildClass initialized")  # This line is executed after the parent class constructor call

# Creating an instance of ChildClass
child = ChildClass()


ChildClass initialized


In [1]:
import torch
x= torch.tensor([1.1, 2.1])
w= torch.tensor([0.1, 0.2])
b= torch.tensor(0.5)


torch.matmul(x, w) + b

tensor(1.0300)

In [10]:
x= torch.tensor([[1.1, 2.1]])


w= torch.tensor([[0.1, 0.2],
                 [0.5, 0.6],
                 [0.8, 0.9]])

b= torch.tensor([0.5, 0.6, 0.7])

torch.matmul(x, w.T) + b


tensor([[1.0300, 2.4100, 3.4700]])

In [8]:
torch.matmul(x, w.T) + b

tensor([[1.0300, 2.4100, 3.4700]])

In [11]:
import torch

class SoftmaxRgression(torch.nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = torch.nn.Linear(num_features, 3)
        
    def forward(self, x):
        return torch.nn.functional.softmax(self.linear(x))
    
    
    
        

In [15]:
import torch
import torch.nn.functional as F

y= torch.tensor([0, 1, 2, 1])
y_one_hot = F.one_hot(y)


In [16]:
y_one_hot

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 1, 0]])

In [18]:
activations = torch.tensor([
    [.8, .1, .1],
    [.2, .7, .1],
    [.1, .2, .7],
    [.1, .8, .1]]
)

In [19]:
activations

tensor([[0.8000, 0.1000, 0.1000],
        [0.2000, 0.7000, 0.1000],
        [0.1000, 0.2000, 0.7000],
        [0.1000, 0.8000, 0.1000]])