In [1]:
import torch


In [6]:
w1 = torch.tensor([.23], requires_grad=True)
b = torch.tensor([.1], requires_grad=True)

In [7]:
x1= torch.tensor([1.23])
y= torch.tensor([1.])

In [10]:
z= w1*x1+b

In [11]:
a = torch.sigmoid(z)

In [13]:
import torch.nn.functional as F

In [14]:
L = F.binary_cross_entropy(a, y)

In [15]:
L

tensor(0.5199, grad_fn=<BinaryCrossEntropyBackward0>)

In [16]:
from torch.autograd import grad

In [19]:
grad_L_w1 = grad(L, w1, retain_graph=True)

In [20]:
grad_L_w1

(tensor([-0.4987]),)

In [21]:
grad_L_b = grad(L, b, retain_graph=True)

In [22]:
grad_L_b

(tensor([-0.4054]),)

In [23]:
L.backward()

In [26]:
w1.grad

tensor([-0.4987])

In [27]:
b.grad

tensor([-0.4054])